package com.middleware.frame.ctrl;

public enum RfidCommand {
    COM_SYS_CFG(0x00),
    COM_SYS_QUERY(0x01),

    /*
    COM_WORKMOD_CFG(2),
    COM_WORKMOD_QUERY(3),
    COM_TEST_CONTROL(10),
    COM_PARA_OP(16),
    */

    COM_UPLOAD_PARA_SET(0x10),
    COM_ANTENNA_SET(0x11),
    COM_ANTENNA_QUERY(0x12),
    COM_CARRYWAVE_SET(0x13),
    COM_CARRYWAVE_QUERY(0x14),
    COM_COMMUNI_SET(0x15),
    COM_COMMUNI_QUERY(0x16),
    COM_NETPARA_SET(0X17),
    COM_NETPARA_QUERY(0x18),
/*
    COM_COMMUNI_SET(21),
    COM_COMMUNI_QUERY(22),
    COM_TAG_SET(25),
    COM_TAG_QUERY(26),
    COM_EXTENDBOARD_SET(27),
    COM_EXTENDBOARD_QUERY(28),
    COM_CARRY_OP(32),
    COM_IO_OP(33),
    COM_INPUT_QUERY(34),
    */

    COM_BUZZER_SET(35),
    COM_BUZZER_QUERY(36),
    COM_READER_REBOOT(42),
    /*
    COM_OPEN_CONN(80),
    COM_CLOSE_CONN(81),
    COM_STOP_READ(83),
    */
    COM_SEND_HEART(0x58),
    /*
    COM_SELECTTAG_SET(96),
    COM_YSEND_READID(97),
    */
    COM_YMAKE_TAGUPLOAD(0x62),
    /*
    COM_YCHK_EID(0x63),
    COM_YREAD_USRDATA(0x64),
    COM_YWRITE_USRDATA(0x65),
    COM_YSET_ACCESSPWD(104),
    COM_YSET_CFGPWD(105),
    COM_YDATA_LOG(106),
    COM_YEAS_SET(107),
    COM_YQUERY_EASFLAG(108),
    COM_YEAS_MON(109),
    */
    COM_YSTOP(0x6F),
    /*
    COM_YTAGCFG_SET(113),
    COM_YTAGCFG_QUERY(114),
    COM_YTAGWORKMODE_SET(115),
    COM_YTAGWORKMODE_QUERY(116),
    COM_YTAGFATSET(117),
    COM_YTAGFATQUERY(118),
    COM_YTAGINITTOFAT(119),
    COM_YTAGSENSORQUERY(120),
    COM_YTAGIOQUERY(121),
    COM_YTAGIOOUT(122),
    COM_6BSELECT_TAG(128),
    COM_6BREAD_UID(129),
    COM_6BREADUSER_DATA(130),
    COM_6BWRITEUSER_DATA(131),
    COM_6BLOCK_TAGDATA(132),
    COM_6BLOCK_QUERY(133),
    COM_6CSELECT_EPCTAG(144),
    COM_6CREAD_EPC(145),
    COM_6CREAD_TID(146),
    COM_6CWRITE_EPCDATA(147),
    COM_6CREADUSER_DATA(148),
    COM_6CWRITEUSER_DATA(149),
    COM_6CBLOCKWRITE_DATA(150),
    COM_6CBLOCKCLEAR_DATA(151),
    COM_6CACCESSPWD_CFG(152),
    COM_6CDESTORYPWD_CFG(153),
    COM_6CLOCK_TAGCFG(154),
    COM_DESTORY_TAG(155),
    COM_EASFLAG_CFG(156),
    COM_EAS_ENABLE(157),
    ENCOURAGE_PARMOP(160),
    ENCOURAGE_SYS_CFG(161),
    ENCOURAGE_SYS_QUERY(162),
    ENCOURAGE_READER_REBOOT(163),
    ENCOURAGE_SEND_HEART(164),
    READER_TIME_SET(176),
    READER_TIME_QUERY(177),
    READER_FLASHDATA_QUERY(178),
    READER_FLASHDATACOUNT_QUERY(179),
    READER_FLASHCLEAR(180),
    GPRS_COMMUNI_SET(192),
    GPRS_COMMUNI_QUERY(193),
    WIFI_COMMUNI_SET(194),
    WIFI_COMMUNI_QUERY(195),
    COM_ENTER_TRANS(196),
    COM_SEND_TRANS(197),
    COM_RECV_TRANS(198),
    COM_MODULE_REBOOT(199),
     */
    COM_DEVICE_REBOOT(0x2A);


    private final int value;


    RfidCommand(int value) {
        this.value = value;
    }

    public byte GetValue() {
        return (byte) this.value;
    }
}


/* Location:              C:\Users\shi_j\Desktop\yrfid_api.jar!\com\yrfidapi\reader\ctrl\RfidCommand.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.2
 */