package com.middleware.frame.common;

public enum RfidStatus {
    RFID_STATUS_OK,

    RFID_ERROR_ALREADY_OPEN,


    RFID_ERROR_BUFFER_TOO_SMALL,

    RFID_ERROR_FAILURE,

    RFID_ERROR_DRIVER_LOAD,

    RFID_ERROR_DRIVER_MISMATCH,


    RFID_ERROR_RESERVED_01,

    RFID_ERROR_INVALID_ANTENNA,

    RFID_ERROR_INVALID_HANDLE,

    RFID_ERROR_INVALID_PARAMETER,

    RFID_ERROR_NO_SUCH_RADIO,

    RFID_ERROR_NOT_INITIALIZED,

    RFID_ERROR_NOT_SUPPORTED,


    RFID_ERROR_OPERATION_CANCELLED,

    RFID_ERROR_OUT_OF_MEMORY,

    RFID_ERROR_RADIO_BUSY,

    RFID_ERROR_RADIO_FAILURE,

    RFID_ERROR_RADIO_NOT_PRESENT,

    RFID_ERROR_CURRENTLY_NOT_ALLOWED,

    RFID_ERROR_RADIO_NOT_RESPONDING,


    RFID_ERROR_NONVOLATILE_INIT_FAILED,


    RFID_ERROR_NONVOLATILE_OUT_OF_BOUNDS,


    RFID_ERROR_NONVOLATILE_WRITE_FAILED,


    RFID_ERROR_RECEIVE_OVERFLOW,

    RFID_ERROR_UNEXPECTED_VALUE,


    RFID_ERROR_NONVOLATILE_CRC_FAILED,

    RFID_ERROR_NONVOLATILE_PACKET_HEADER,

    RFID_ERROR_NONVOLATILE_MAX_PACKET_LENGTH,

    RFID_ERROR_READ_DATA_ERRO,
    RFID_ERROR_READ_DATA_CRC_ERRO,
    RFID_ERROR_READ_TIME_OUT,
    RFID_ERROR_INVALID_COMMAND,
    RFID_ERROR_COMMAND_EXEING,
    RFID_ERROR_READING_NOTEXE,
    RFID_ERROR_REV_ERRO,
    RFID_ERROR_POINTER_NULL,
    RFID_ERROR_SIZE_ZERO,
    RFID_ERROR_NO_CARD,
    RFID_ERROR_STATE_ERRO
}


/* Location:              C:\Users\shi_j\Desktop\yrfid_api.jar!\com\yrfidapi\common\RfidStatus.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.2
 */